<wsdl:definitions xmlns:tns="http://activebpel.org/swDef" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" targetNamespace="http://activebpel.org/swDef">
	<wsdl:message name="swRequest"/>
	<wsdl:message name="swResponse">
		<wsdl:part name="swReturn" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="swServicePT">
		<wsdl:operation name="sw">
			<wsdl:input name="entrada" message="tns:swRequest"/>
			<wsdl:output name="salida" message="tns:swResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="swServiceSoapBinding" type="tns:swServicePT">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="sw">
			<wsdlsoap:operation/>
			<wsdl:input>
				<wsdlsoap:body xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://activebpel.org/swDef"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://activebpel.org/swDef"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="swServiceService">
		<wsdl:port name="swService" binding="tns:swServiceSoapBinding">
			<wsdlsoap:address location="http://localhost:8080/active-bpel/swDef" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"/>
		</wsdl:port>
	</wsdl:service>
	<plnk:partnerLinkType name="swLT">
		<plnk:role name="swRol">
			<plnk:portType name="tns:swServicePT"/>
		</plnk:role>
	</plnk:partnerLinkType>
</wsdl:definitions>
